In [14]:
import pandas as pd
import numpy as np
import csv 
import chardet
import seaborn as sns

In [15]:
from sklearn.preprocessing import LabelEncoder ,OneHotEncoder

In [16]:
wa_fn=pd.read_csv("M:\ITI MAT\data prep and visualization\data prep\ITI DEP 2023\pandas lab\WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [17]:
wa_fn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

In [18]:
#wa_fn["Attrition"]=pd.get_dummies(wa_fn["Attrition"], drop_first=True)

In [19]:
lableencoder =LabelEncoder()
wa_fn["Attrition_new"]=lableencoder.fit_transform(wa_fn["Attrition"])
wa_fn["Attrition_new2"]=lableencoder.inverse_transform(wa_fn["Attrition_new"])


In [20]:
wa_fn

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  StockOptionLevel TotalWorkingYears  \
0                  1  ...                 0                 8   
1                  2  ...                 1                10   
2                  4  ...                 0                 7   
3                  5  ...                 0                 8   
4                  7  ...                 1                 6   
...              ...  ...               ...               ...   
1465            2061  ...                 1                17   
1466            2062  ...                 1                 9   
1467            2064  ...                 1                 6   
1468            2065  ...                 0                17   
1469            2068  ...                 0                 6   

      TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                         0                1               6   
1                         3                3              10   
2                         3                3               0   
3                         3                3               8   
4                         3                3               2   
...                     ...              ...             ...   
1465                      3                3               5   
1466                      5                3               7   
1467                      0                3               6   
1468                      3                2               9   
1469                      3                4               4   

     YearsInCurrentRole  YearsSinceLastPromotion YearsWithCurrManager  \
0                     4                        0                    5   
1                     7                        1                    7   
2                     0                        0                    0   
3                     7                        3                    0   
4                     2                        2                    2   
...                 ...                      ...                  ...   
1465                  2                        0                    3   
1466                  7                        1                    7   
1467                  2                        0                    3

In [25]:
cat= list(wa_fn.select_dtypes(include="object").columns)
cat

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime',
 'Attrition_new2']

In [24]:
onehot = OneHotEncoder()
wa_fn_onehot= onehot.fit_transform(wa_fn[cat])
print(wa_fn_onehot.toarray())

[[0. 1. 0. ... 1. 0. 1.]
 [1. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 1. 0. 1.]
 ...
 [1. 0. 0. ... 1. 1. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 1. 0.]]


In [26]:
onehot.get_feature_names_out()

array(['Attrition_No', 'Attrition_Yes', 'BusinessTravel_Non-Travel',
       'BusinessTravel_Travel_Frequently', 'BusinessTravel_Travel_Rarely',
       'Department_Human Resources', 'Department_Research & Development',
       'Department_Sales', 'EducationField_Human Resources',
       'EducationField_Life Sciences', 'EducationField_Marketing',
       'EducationField_Medical', 'EducationField_Other',
       'EducationField_Technical Degree', 'Gender_Female', 'Gender_Male',
       'JobRole_Healthcare Representative', 'JobRole_Human Resources',
       'JobRole_Laboratory Technician', 'JobRole_Manager',
       'JobRole_Manufacturing Director', 'JobRole_Research Director',
       'JobRole_Research Scientist', 'JobRole_Sales Executive',
       'JobRole_Sales Representative', 'MaritalStatus_Divorced',
       'MaritalStatus_Married', 'MaritalStatus_Single', 'Over18_Y',
       'OverTime_No', 'OverTime_Yes', 'Attrition_new2_No',
       'Attrition_new2_Yes'], dtype=object)